/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ServiceProvider.electrcian;

import Business.Customer.CustomerBilling;
import Business.EcoSystem;
import Business.Network;
import Business.PropertyManagement.ServiceRequest;
import Business.User.User;
import Business.User.UserDirectory;
import UI.MainJFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ElectricianJFrame extends javax.swing.JFrame {

    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel2;
    DefaultTableModel tableModel1;
    
    /**
     * Creates new form ElectricianJFrame
     */
    public ElectricianJFrame() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
    }
    
    public ElectricianJFrame(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel2 = (DefaultTableModel) jTable2.getModel();
        this.tableModel1 = (DefaultTableModel) jTable1.getModel();
        
       // titlemain.setText(user.getRoleType() + " Section");
        jLabel6.setText(this.user.getFirstName());
        jLabel6.setText(this.user.getRoleType());
        jLabel12.setText(this.user.getUserName());
        
        populaterequests();
        populatecompletedrequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populaterequests(){
        // Table 1
        tableModel1.setRowCount(0);
        // System.out.println(this.network.getPropertyDirectory().getProperties().size());
        for(ServiceRequest sr : this.network.getServicerequestdirectory().getServicerequestlist()){
                    if (sr.getServiceprovider() == null) {
                        
                        
                    } 
                    else {
                        if (sr.getServiceprovider().getUserId().equals(this.user.getUserId()) && sr.getService_status().equals("Service Provider Assigned")){
                        Object[] row = new Object[7];

                        row[0] = sr;
                        row[1] = sr.getCustomer().getFullName();
                        row[2] = sr.getService_subject();
                        row[3] = sr.getService_desc();
                        row[4] = sr.getCustomer().getPhoneNumber();
                        row[5] = sr.getCustomer().getAddress();
                        row[6] = "Pending";

                        tableModel1.addRow(row);

                        } else {
                            //System.out.println("This is the inner most Else, So no users are found...");
                        }
                    }
                //System.out.println("Reached the for loop of service provider");
        }
    }
    
    public void populatecompletedrequests(){
        tableModel2.setRowCount(0);
        // System.out.println(this.network.getPropertyDirectory().getProperties().size());
        for(ServiceRequest sr : this.network.getServicerequestdirectory().getServicerequestlist()){
            if (sr.getServiceprovider() == null ){
                
            } else {
                
                if (sr.getServiceprovider().getUserId().equals(this.user.getUserId()) && sr.getService_status().equals("Completed")){
                    Object[] row = new Object[5];

                    row[0] = sr.toString();
                    row[1] = sr.getCustomer().getFullName();
                    row[2] = sr.getServiceProvider_comment();
                    row[3] = sr.getService_price();
                    row[4] = sr.getService_status();

                    tableModel2.addRow(row);
                }  
            }                   
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jServiceCost = new javax.swing.JTextField();
        ServiceCompleteBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jServiceComments = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Service ID", "Customer", "Service Comment", "Service Price", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 1010, 120));
        jPanel1.add(jServiceCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 120, 30));

        ServiceCompleteBtn.setBackground(new java.awt.Color(41, 67, 138));
        ServiceCompleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ServiceCompleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        ServiceCompleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        ServiceCompleteBtn.setText("Complete");
        ServiceCompleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceCompleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ServiceCompleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 130, 40));

        jButton2.setBackground(new java.awt.Color(41, 67, 138));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 120, 40));
        jPanel1.add(jServiceComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 219, 30));

        jTable1.setForeground(new java.awt.Color(41, 67, 138));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Service ID", "Customer", "Subject", "Service Details", "Customer Contact", "Customer Address", "Status"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 1010, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 67, 138));
        jLabel2.setText("Service Cost: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("Billing Comments :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 120, -1));

        jLabel4.setBackground(new java.awt.Color(41, 67, 138));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(41, 67, 138));
        jLabel4.setText("Designation: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel6.setBackground(new java.awt.Color(41, 67, 138));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(41, 67, 138));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 110, 20));

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(41, 67, 138));
        jLabel8.setText("Service Provider Panel");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel11.setBackground(new java.awt.Color(41, 67, 138));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(41, 67, 138));
        jLabel11.setText("Username: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, 20));

        jLabel12.setBackground(new java.awt.Color(41, 67, 138));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(41, 67, 138));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 100, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/electricity-1.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 560, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainJFrame mj = new MainJFrame(this.ecosystem, this.user);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ServiceCompleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceCompleteBtnActionPerformed
        // TODO add your handling code here:

        try {
            
            int enteredPrice = Integer.parseInt(jServiceCost.getText());
            String ServiceComment = jServiceComments.getText();
            
            int selectedRowIndex = jTable1.getSelectedRow();
            ServiceRequest selectedServiceRequest = (ServiceRequest) tableModel1.getValueAt(selectedRowIndex, 0);
            
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to approve.");
                return;
            }
            
            this.network.getServicerequestdirectory().updatServiceStatus(selectedServiceRequest, ServiceComment, "Completed", enteredPrice);

            //User definition for email notif
            User getUser = network.getUserDirectory().getUserById(selectedServiceRequest.getCustomer().getUserId());
            
            float Service_FinalPrice = enteredPrice;
            
            CustomerBilling ct = new CustomerBilling();
            ct.setUserId(selectedServiceRequest.getCustomer().getUserId());
            ct.setFacilityUsed(ServiceComment);
            ct.setPrice(Service_FinalPrice);
            network.getCustomerbillingdirectory().addCustomerBilling(ct);

            //email notification
            //new EmailNotification().SendEmailOfNotification(getUser, "Laundry");

            JOptionPane.showMessageDialog(this, "Request approved successfully and email notification sent");
            
            
            populatecompletedrequests();
            populaterequests();
            jServiceCost.setText("");
            jServiceComments.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_ServiceCompleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElectricianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElectricianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElectricianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElectricianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElectricianJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ServiceCompleteBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jServiceComments;
    private javax.swing.JTextField jServiceCost;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
