/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Canteen;

import Business.Canteen.MealPlan;
import Business.EcoSystem;
import Business.Network;
import Business.User.User;
import Business.User.UserDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ManageFoodMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFoodMenuJPanel
     */
    
    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    
    String mainValidationString = "";
    String validationString1 = "";
    String validationString2 = "";
    
    public ManageFoodMenuJPanel() {
        initComponents();
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
    }
    
    public ManageFoodMenuJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        
        showMenuData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void resetMenuData() {
        try {
            jTextField1.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextArea1.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public boolean areDataFieldsEmpty() {
            validationString1 = "";
            if (jTextField1.getText().isEmpty()) {
                validationString1 += "Id, ";
            }
            if (jTextField3.getText().isEmpty()) {
                validationString1 += "Name, ";
            }
            if (jTextField4.getText() == null) {
                validationString1 += "Price, ";
            }
            if (jTextArea1.getText() == null) {
                validationString1 += "Description, ";
            }
            return isNotValid(validationString1);
    }

    public boolean areDataTypesCorrect() {
            validationString2 = "";
            if (!validateDoubleDataType(jTextField4.getText())) {
                validationString2 += "Price, ";
            }
            return isNotValid(validationString2);
    }

    public boolean isNotValid(String str) {
            if (str.equals("")) {
                return false;
            } else {
                return true;
            }
    }

    public boolean validateDoubleDataType(String str) {
        try {
            Double.parseDouble(str);
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }

    public void validationErrorMessagesDialog(boolean validation1, boolean validation2) {
            if (validation1) {
                mainValidationString = validationString1;
                JOptionPane.showMessageDialog(this, "Please update the data for these fields: " + mainValidationString);
            } else if (validation2) {
                mainValidationString = validationString2;
                JOptionPane.showMessageDialog(this, "Please enter only numbers for these fields: " + mainValidationString);
            }
    }

    private boolean menuDetailsExistence() {
            String menuId = jTextField1.getText();
            boolean exist = false;
            for (MealPlan fb : network.getMealPlanDirectory().getMealPlanDirectory()){
                if (menuId.equals(fb.getMealId())) {
                    exist = true;
                    break;
                }
            }
            return exist;
    }

    private MealPlan setMenuData() {
            String menuId = jTextField1.getText();
            String category = String.valueOf(jComboBox1.getSelectedItem());
            String name = jTextField3.getText();
            String foodDesc = jTextArea1.getText();
            double price = Double.parseDouble(jTextField4.getText());

            MealPlan fb = new MealPlan();
                fb.setMealId(menuId);
                fb.setCategory(category);
                fb.setMealName(name);
                fb.setMealDescription(foodDesc);
                fb.setPrice(price);

            return fb;
    }

    private void showMenuData() {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (MealPlan fb : network.getMealPlanDirectory().getMealPlanDirectory()) {

                Object[] newRow = new Object[5];
                newRow[0] = fb;
                newRow[1] = fb.getCategory();
                newRow[2] = fb.getMealName();
                newRow[3] = fb.getMealDescription();
                newRow[4] = fb.getPrice();

                model.addRow(newRow);
            }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Category", "Name", "Description", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 760, 120));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 130, 30));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 67, 138));
        jLabel2.setText("Description :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 67, 138));
        jLabel3.setText("Category :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(41, 67, 138));
        jLabel4.setText("Name :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(41, 67, 138));
        jLabel5.setText("Price :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast", "Brunch", "Lunch", "Evening Snacks", "Dinner", "Late Night Dinner", "Other Meals" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 130, 30));

        jButton1.setBackground(new java.awt.Color(41, 67, 138));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 130, 40));

        jButton2.setBackground(new java.awt.Color(41, 67, 138));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 130, 40));

        jButton3.setBackground(new java.awt.Color(41, 67, 138));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        jButton3.setText("View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 130, 40));

        jButton4.setBackground(new java.awt.Color(41, 67, 138));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 440, 130, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(41, 67, 138));
        jLabel6.setText("ID :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 30, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 660, 60));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("Create Meal Plans");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mealCreate.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 570, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEditable(true);
        try {
            boolean validation1 = areDataFieldsEmpty();
            boolean validation2 = areDataTypesCorrect();

            if (!validation1 && !validation2) {
                String menuId = jTextField1.getText();
                if (!menuDetailsExistence()) {
                    network.getMealPlanDirectory().addNewMenuData(setMenuData());
                    JOptionPane.showMessageDialog(this, "New Meal data with MealId id : " + menuId + " created");
                    resetMenuData();
                    showMenuData();
                } else {
                    JOptionPane.showMessageDialog(this, "Meal details already exists with the MealId : " + menuId);
                    resetMenuData();
                }
            } else {
                validationErrorMessagesDialog(validation1, validation2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String menuId = jTextField1.getText();
            boolean validation1 = areDataFieldsEmpty();

            if (!validation1) {
                if (menuDetailsExistence()) {
                    MealPlan updatedMenuData = setMenuData();
                    int index = 0;
                    for (MealPlan fb : network.getMealPlanDirectory().getMealPlanDirectory()) {
                        if (menuId.equals(fb.getMealId())) {
                            network.getMealPlanDirectory().updateExistingMenuData(updatedMenuData, index);
                            break;
                        }
                        index++;
                    }
                    JOptionPane.showMessageDialog(this, "Existing Meal details with Meal id : " + menuId + " updated");
                    resetMenuData();
                    showMenuData();
                } else {
                    JOptionPane.showMessageDialog(this, "You can't update the Meal details since Meal with Meal id : " + menuId + " doesn't exist");
                }
            } else {
                validationErrorMessagesDialog(validation1, false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            int index = jTable1.getSelectedRow();

            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to be viewed");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            MealPlan selectedMenuItem = (MealPlan) model.getValueAt(index, 0);

            jTextField1.setText(selectedMenuItem.getMealId());
            jTextField1.setEditable(false);
            jComboBox1.setSelectedItem(selectedMenuItem.getCategory());
            jTextField3.setText(selectedMenuItem.getMealName());
            jTextArea1.setText(selectedMenuItem.getMealDescription());
            jTextField4.setText(String.valueOf(selectedMenuItem.getPrice()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRowIndex = jTable1.getSelectedRow();
            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select a row to delete.");
                return;
            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            MealPlan selectedMenuItem = (MealPlan) model.getValueAt(selectedRowIndex, 0);
            network.getMealPlanDirectory().deleteMenuData(selectedMenuItem);
            JOptionPane.showMessageDialog(this, "Selected menu data deleted");
            resetMenuData();
            showMenuData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
