/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


public class AboutJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutJPanel
     */
    public AboutJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 241, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("Shalom Daniel : 002746121");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 250, 30));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 67, 138));
        jLabel2.setText("Aseem Deshmukh : 002743798");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 270, 30));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 67, 138));
        jLabel3.setText("Nishant Patel : 002796854");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 240, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/groupphoto-1.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 350, 520));

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(41, 67, 138));
        jLabel8.setText("Founders of the Project :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 250, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
