
package UI;

//import Business.DB4OUtil.DB4OUtil;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Network;
import Business.User.User;
import Business.User.UserDirectory;
import Database.mysql_db_connection;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


public class Register extends javax.swing.JPanel {

    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    private SendEmail se;
    
    
    private static class scnMax {

        private static int bottom;

        public scnMax() {
        }
    }  
    
    public Register() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
        
         
        // Screen size as per all resolution types:
            
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        Insets scnmax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = Register.scnMax.bottom;
        this.setSize(xsize, ysize - taskBarSize);
        
    }
    
    public Register(EcoSystem ecosystem, User user) {
        initComponents();
        
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.se = new SendEmail();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("First Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, -1));

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });
        add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, -1));
        add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 140, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 140, -1));

        btnRegister.setBackground(new java.awt.Color(41, 67, 138));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regUser.png"))); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 120, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 67, 138));
        jLabel2.setText("User Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 67, 138));
        jLabel3.setText("Last Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(41, 67, 138));
        jLabel4.setText("Password :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 90, -1));
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 130, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(41, 67, 138));
        jLabel10.setText("Age :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 60, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(41, 67, 138));
        jLabel11.setText("Phone Number :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 110, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 130, -1));

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(41, 67, 138));
        jLabel13.setText("Register Now!");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 190, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(41, 67, 138));
        jLabel14.setText("Email Address :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, -1));

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });
        add(txtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.gif"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 630, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
//        // TODO add your handling code here:
        
        mysql_db_connection db = new mysql_db_connection();

        if (txtFName.getText().isEmpty() || txtLName.getText().isEmpty() || txtUserName.getText().isEmpty()|| txtPassword.getText().isEmpty()
                || txtAge.getText().isEmpty()|| txtPhoneNumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all details !");
            clearAllFields();
            return;
        }else if (validatePhoneNumber(txtPhoneNumber.getText()) == null) {
            JOptionPane.showMessageDialog(this, "Please enter a valid phone number !");
            return;
        }else if(validateEmailAddress(txtEmailAddress.getText()) == null) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address !");
            return;
        }else if (validateAge(txtAge.getText()) == null) {
            JOptionPane.showMessageDialog(this, "Please enter a valid age!");
            return;
        }else{

            UUID uuid = UUID.randomUUID();
            String randomUUIDString = uuid.toString();

            String firstName = txtFName.getText();
            String lastName = txtLName.getText();
            String userName = txtUserName.getText();
            String password = txtPassword.getText();
            Integer age = Integer.valueOf(txtAge.getText());
            Long phoneNumber = Long.valueOf(txtPhoneNumber.getText());
            String userId = randomUUIDString;
            String emailAddress = txtEmailAddress.getText();
            String role = "Customer";

            this.userDirectory.createUserAccount(userName, password, role, userId);
            CustomerDirectory customerDirectory = this.network.getCustomerDirectory();
            customerDirectory.createCustomerProfile(userId, firstName, lastName, userName, password, age, emailAddress, phoneNumber);
            db.db_conn(userId, firstName, lastName,userName, password, age, emailAddress, phoneNumber);

            System.out.println("UD size : "  + this.userDirectory.getUsers().size());
            System.out.println("CD size : "  + customerDirectory.getCustomerlist().size());

            clearAllFields();

            se.sendmail(firstName, lastName, emailAddress); 
            
            JOptionPane.showMessageDialog(null, "Congrats! You have been successfully registered. Please check your inbox for an email! :) ");
            
        }
  
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private Integer validateAge(String age) {
        try {
            return Integer.parseInt(age);
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            return null;
        }
    }

    private Long validatePhoneNumber(String phoneNumber) {
        try {

            String cellPhoneNumberRegex = "^\\d{10}$";

            Pattern cellPhoneNumberPattern = Pattern.compile(cellPhoneNumberRegex);
            Matcher cellPhoneNumberMatcher = cellPhoneNumberPattern.matcher(phoneNumber);

            if (cellPhoneNumberMatcher.matches()) {
                return Long.parseLong(phoneNumber);
            } else {
                //JOptionPane.showMessageDialog(this, "Invalid Phone Number!");
                return null;
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            return null;
        }

    }
    
    private String validateEmailAddress(String emailAddress) {
        try {

            String emailAddressRegex = "^(.+)@(\\S+)$";

            Pattern emailPattern = Pattern.compile(emailAddressRegex);
            Matcher emailMatcher = emailPattern.matcher(txtEmailAddress.getText());

            if (emailMatcher.matches()) {
                return emailAddress;
            } else {
//                JOptionPane.showMessageDialog(this, "Invalid Email Address!");
                return null;
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void clearAllFields() {
        txtAge.setText("");
        txtFName.setText("");
        txtLName.setText("");
        txtPassword.setText("");
        txtPhoneNumber.setText("");
        txtUserName.setText("");
        txtEmailAddress.setText("");
    }

}
