/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.RealEstate;

import UI.OpenStreetMaps.GMapsFrame;
import Business.EcoSystem;
import Business.Network;
import Business.RealEstate.Property;
import Business.User.User;
import Business.User.UserDirectory;
import UI.OpenStreetMaps.GMapsFrame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shalom Daniel <your.name at your.org>
 */
public class ViewPropertyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPropertyJPanel
     */
    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel; 
    Property selectedProperty ;
    
    public ViewPropertyJPanel() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
        
    }
    
    public ViewPropertyJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        populate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setForeground(new java.awt.Color(41, 67, 138));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property ID", "No of Rooms", "No of Bathrooms", "Address", "Rent price", "Start Date", "Lease Type", "Is Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 790, 140));

        jButton3.setBackground(new java.awt.Color(41, 67, 138));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapmarker.png"))); // NOI18N
        jButton3.setText("View Location");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 50));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("View Property");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img1.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 480, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = jTable1.getSelectedRow();
        
        if(selectedRow >= 0){
            this.selectedProperty = (Property) jTable1.getValueAt(selectedRow, 0);
            
            GMapsFrame gMapsFrame = new GMapsFrame(selectedProperty);
            gMapsFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            gMapsFrame.setVisible(true);
//            new GMapsFrame(gMapsFrame, selectedProperty);
                    
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row ");
        } 
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void populate(){
        
        tableModel.setRowCount(0);
//        System.out.println(this.network.getPropertyDirectory().getProperties().size());
        for(Property p : this.network.getPropertyDirectory().getProperties()){
            Object[] row = new Object[10];

            row[0] = p;
            row[1] = p.getNo_of_rooms();
            row[2] = p.getNo_of_bathrooms();
            row[3] = p.getFull_address();
            row[4] = p.getPrice();
            row[5] = p.getLease().getStart_date();
            row[6] = p.getLease().getType();
            row[7] = p.getIsAvailable();

            tableModel.addRow(row);

        }    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
