/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.RealEstate;

import Business.Customer.Customer;
import Business.Customer.CustomerBilling;
import Business.EcoSystem;
import Business.Network;
import Business.Services.RentalRequest;
import Business.User.User;
import Business.User.UserDirectory;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shalom Daniel <your.name at your.org>
 */
public class ViewCustomersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomers
     */
    
    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel; 
    Customer selectedCustomer ;
    
    public ViewCustomersJPanel() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
        
    }
    
    public ViewCustomersJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        populate();
        
    }
    
    
    
    public void populate() {
        
        tableModel.setRowCount(0);
        for(Customer c : this.network.getCustomerDirectory().getCustomerlist()){
            for(RentalRequest r : c.getCustomerRentalList()){
                if(r.getApplication_status() == null){
                
                }else if(r.getApplication_status().equals("Accepted")){
                    
                   Object[] row = new Object[10];

                   row[0] = c.getProperty();
                   row[1] = c.getProperty().getFull_address(); 
                   row[2] = c; 
                   row[3] = c.getFirstName() + c.getLastName(); 
                   row[4] = c.getAge(); 
                   row[5] = c.getEmailId();
                   row[6] = c.getPhoneNumber();
                   row[7] = c.getProperty().getLease().getIsLeaseSigned();
                   row[8] = c.getProperty().getLease().getType();

                   tableModel.addRow(row);                      
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setForeground(new java.awt.Color(41, 67, 138));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property ID", "Address ", "Customer ID", "Name", "Age", "Email ID", "Phone No", "Lease Agreement", "Lease Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 920, 170));

        jButton1.setBackground(new java.awt.Color(41, 67, 138));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("Approve Lease Agreement ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 220, 50));

        jButton2.setBackground(new java.awt.Color(41, 67, 138));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        jButton2.setText("View Lease Contract");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 220, 50));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("Customer Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cust-3.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 640, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = jTable1.getSelectedRow();

        if(selectedrow >= 0){
            this.selectedCustomer = (Customer) jTable1.getValueAt(selectedrow, 2);
            this.selectedCustomer.getProperty().getLease().setIsLeaseSigned(true);
            this.selectedCustomer.setActvity_status(true);
            
            CustomerBilling ct = new CustomerBilling();
            ct.setUserId(selectedCustomer.getUserId());
            ct.setFacilityUsed("Total Rent Amount");
            ct.setPrice(selectedCustomer.getRentalsTotal());
            this.network.getCustomerbillingdirectory().addCustomerBilling(ct);
            JOptionPane.showMessageDialog(null, "Lease contract approved! Customer will be notified.");
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row ");
        }  
        
        populate(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = jTable1.getSelectedRow();

        if(selectedrow >= 0){
            
            this.selectedCustomer = (Customer) jTable1.getValueAt(selectedrow, 2);
            
            try{
                File file = new File (selectedCustomer.getProperty().getLease().getLeaseDoc());
                if(file.exists()){
                    if(Desktop.isDesktopSupported()){
                        Desktop.getDesktop().open(file);
                    }else{
                        JOptionPane.showMessageDialog(this, "This file is not supported.");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "This file does not exist.");
                }
            }catch(Exception e){
                 JOptionPane.showMessageDialog(this, "This file does not exist.");
//                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row ");
        }  
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
