/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.RealEstate;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Network;
import Business.RealEstate.Property;
import Business.Services.RentalRequest;
import Business.User.User;
import Business.User.UserDirectory;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class ViewRentalRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewRentalRequestsJPanel
     */
    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel; 
    RentalRequest selectedRequest ;
    
    
    public ViewRentalRequestsJPanel() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
        
    }
    
    public ViewRentalRequestsJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        populate();
        formatRows();
    }
    
        
    public void populate() {
        
        tableModel.setRowCount(0);
        
        for(RentalRequest r : this.network.getRentalRequestDirectory().getRentalList()){
                
                Object[] row = new Object[10];

                row[0] = r;
                row[1] = r.getCustomer().getFullName();
                row[2] = r.getCustomer().getAge();
                row[3] = r.getCustomer().getEmailId();
                row[4] = r.getCustomer().getPhoneNumber();
                row[5] = r.getProperty().getID();
                row[6] = r.getProperty().getFull_address();
                row[7] = r.getLease().getType();  
                row[8] = String.valueOf(r.getProperty().getIsAvailable());
                row[9] = r.getApplication_status();
                
                tableModel.addRow(row);                

        }
    }
    
    private void formatRows() {

        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = String.valueOf(tableModel.getValueAt(row, 9));
                c.setBackground(status.equals("Application in Progress") ? Color.GRAY : status.equals("Accepted") ? Color.GREEN : Color.RED);
                return c;
            }
        });

    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setForeground(new java.awt.Color(41, 67, 138));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rental Request ID ID", "Customer Name", "Age", "Email ID", "Phone No", "Property ID", "Apartment Address", "Lease Type", "Availability Status", "Application Request status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 980, 150));

        jButton1.setBackground(new java.awt.Color(41, 67, 138));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 120, 40));

        jButton2.setBackground(new java.awt.Color(41, 67, 138));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 120, 40));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("View Rental Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 190, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/custrental-1.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 570, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int selectedrow = jTable1.getSelectedRow();

        if(selectedrow >= 0){
            this.selectedRequest = (RentalRequest) jTable1.getValueAt(selectedrow, 0);
            this.selectedRequest.getProperty().setIsAvailable(false);
            this.selectedRequest.setApplication_status("Accepted");
//            this.selectedRequest.getCustomer().addOrder(this.selectedRequest);
            Float r = this.selectedRequest.getCustomer().calculateRentPrice(this.selectedRequest.getLease().getType(), this.selectedRequest.getProperty().getPrice()); 
            this.selectedRequest.getCustomer().setRentalsTotal(r);  
            this.selectedRequest.getCustomer().setProperty(this.selectedRequest.getProperty());
            JOptionPane.showMessageDialog(null, "This request has been Accepted! Customer will be notified. ");
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row ");
        }  
        
        populate();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = jTable1.getSelectedRow();

        if(selectedrow >= 0){
            this.selectedRequest = (RentalRequest) jTable1.getValueAt(selectedrow, 0);
            this.selectedRequest.setApplication_status("Rejected");
            JOptionPane.showMessageDialog(null, "This request has been Rejected! Customer will be notified.");
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row ");
        }  
        
        populate();     
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
