/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Network;
import Business.Services.RentalRequest;
import Business.User.User;
import Business.User.UserDirectory;
import UI.MainJFrame;
import UI.RealEstate.ViewPropertyJPanel;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class CustomerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerJFrame
     */
    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
     
    
    public CustomerJFrame() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
        
    }
    
    public CustomerJFrame(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        
        Customer c = this.network.getCustomerDirectory().findCustomer(user.getUserId());
        fieldCustomerName.setText("Welcome " + c.getFirstName() + " ! ");
        
        
        RentalRequest r = this.network.getRentalRequestDirectory().findById(c);
        if(r == null){

        }else{
            if(r.getApplication_status() == null) {
                
            }
            else if((r.getApplication_status().equals("Accepted")) && (r.getLease().getIsLeaseSigned().equals(false))) {
                JOptionPane.showMessageDialog(null, "Good news! Your Rental application has been accepted. You may now proceed to sign the lease of your new apartment. \n Complete Lease agreement to access listed services. ");
            }else if(r.getApplication_status() == null){
                JOptionPane.showMessageDialog(null, "Sorry :) \n" + " Your Rental application has been rejected. The apartment you are looking for maybe unavailable at this time or has been sold to somebody else. \n You can view other properties. Thankyou! ");
            }else{
                
            }           
        }
        
        if(c.getProperty().getLease().getIsLeaseSigned().equals(false)){  
            bookRoomBTN.setEnabled(false);
            viewBookedRoomBTN.setEnabled(false);
            RequestLaundaryjBtn.setEnabled(false);
            RequestMealjBtn.setEnabled(false);
            RequestServicejBtn.setEnabled(false);         
        }else{
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        fieldCustomerName = new javax.swing.JLabel();
        RequestMealjBtn = new javax.swing.JButton();
        RequestServicejBtn = new javax.swing.JButton();
        bookRoomBTN = new javax.swing.JButton();
        viewBookedRoomBTN = new javax.swing.JButton();
        RequestLaundaryjBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        jButton6.setText("Current Room Bookings");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setText("Book Recreation Rooms");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("My Current Property");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldCustomerName.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        jPanel1.add(fieldCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 250, 40));

        RequestMealjBtn.setBackground(new java.awt.Color(41, 67, 138));
        RequestMealjBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RequestMealjBtn.setForeground(new java.awt.Color(255, 255, 255));
        RequestMealjBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reqmeal.png"))); // NOI18N
        RequestMealjBtn.setText("Request Meal");
        RequestMealjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestMealjBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RequestMealjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 210, 50));

        RequestServicejBtn.setBackground(new java.awt.Color(41, 67, 138));
        RequestServicejBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RequestServicejBtn.setForeground(new java.awt.Color(255, 255, 255));
        RequestServicejBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reqservice.png"))); // NOI18N
        RequestServicejBtn.setText("Request Service");
        RequestServicejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestServicejBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RequestServicejBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 240, 50));

        bookRoomBTN.setBackground(new java.awt.Color(41, 67, 138));
        bookRoomBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookRoomBTN.setForeground(new java.awt.Color(255, 255, 255));
        bookRoomBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        bookRoomBTN.setText("Book Recreation Rooms");
        bookRoomBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomBTNActionPerformed(evt);
            }
        });
        jPanel1.add(bookRoomBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 210, 50));

        viewBookedRoomBTN.setBackground(new java.awt.Color(41, 67, 138));
        viewBookedRoomBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewBookedRoomBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewBookedRoomBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/purchaseOrder.png"))); // NOI18N
        viewBookedRoomBTN.setText("Current Room Bookings");
        viewBookedRoomBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookedRoomBTNActionPerformed(evt);
            }
        });
        jPanel1.add(viewBookedRoomBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 240, 50));

        RequestLaundaryjBtn.setBackground(new java.awt.Color(41, 67, 138));
        RequestLaundaryjBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RequestLaundaryjBtn.setForeground(new java.awt.Color(255, 255, 255));
        RequestLaundaryjBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reqlaundry.png"))); // NOI18N
        RequestLaundaryjBtn.setText("Request Laundry");
        RequestLaundaryjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestLaundaryjBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RequestLaundaryjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 180, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cust-2.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1200, 1000));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 1010, 530));

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(41, 67, 138));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeBtn.png"))); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 50));

        jButton2.setBackground(new java.awt.Color(41, 67, 138));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        jButton2.setText("View Property Listings ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 50));

        jButton5.setBackground(new java.awt.Color(41, 67, 138));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 200, 50));

        jButton9.setBackground(new java.awt.Color(41, 67, 138));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeBtn.png"))); // NOI18N
        jButton9.setText("My Current Property");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 50));

        jButton10.setBackground(new java.awt.Color(41, 67, 138));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        jButton10.setText("View My Requests");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 50));

        jButton13.setBackground(new java.awt.Color(41, 67, 138));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money.png"))); // NOI18N
        jButton13.setText("View Billing");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 200, 50));

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1270, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        CustomerJFrame cj = new CustomerJFrame(this.ecosystem, this.user);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CustomerViewPropertyJPanel(ecosystem, user));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        MainJFrame mj = new MainJFrame(this.ecosystem, this.user);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void RequestServicejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestServicejBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ElectricityServiceJPanel(ecosystem, user));
    }//GEN-LAST:event_RequestServicejBtnActionPerformed

    private void RequestMealjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestMealjBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new RequestMealPlanJPanel(ecosystem, user));
    }//GEN-LAST:event_RequestMealjBtnActionPerformed

    private void RequestLaundaryjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestLaundaryjBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new RequestLaundaryJPanel(ecosystem, user));
    }//GEN-LAST:event_RequestLaundaryjBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewCustomerCurrentBookingsJPanel(ecosystem, user));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new BookRecreationRoomsJPanel(ecosystem, user));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CustomerCurrentPropertyJPanel(ecosystem, user));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewBookedRoomBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookedRoomBTNActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewCustomerCurrentBookingsJPanel(ecosystem, user));
    }//GEN-LAST:event_viewBookedRoomBTNActionPerformed

    private void bookRoomBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomBTNActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new BookRecreationRoomsJPanel(ecosystem, user));
    }//GEN-LAST:event_bookRoomBTNActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Customer c = this.network.getCustomerDirectory().findCustomer(user.getUserId());
        if(c.getProperty().getID() == null){
            JOptionPane.showMessageDialog(null, "You do not have any properties yet. But you can rent one right away!! :) \n\n Go to View Property Listings Panel ");

        }else{
            jSplitPane1.setRightComponent(new CustomerCurrentPropertyJPanel(ecosystem, user)); 
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewCustomerRentalRequestsJPanel(ecosystem, user));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new BillingJPanel(ecosystem, user));
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestLaundaryjBtn;
    private javax.swing.JButton RequestMealjBtn;
    private javax.swing.JButton RequestServicejBtn;
    private javax.swing.JButton bookRoomBTN;
    private javax.swing.JLabel fieldCustomerName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton viewBookedRoomBTN;
    // End of variables declaration//GEN-END:variables
}
