/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Network;
import Business.RealEstate.Property;
import Business.User.User;
import Business.User.UserDirectory;
import UI.OpenStreetMaps.GMapsFrame;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shalom Daniel <your.name at your.org>
 */
public class CustomerCurrentPropertyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPropertyJPanel
     */
    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel; 
    Property selectedProperty ;
    
    public CustomerCurrentPropertyJPanel() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
        
    }
    
    public CustomerCurrentPropertyJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel = (DefaultTableModel) jTable2.getModel();   
        
        populate();
        
    }
    
    public void populate(){
        
        Customer c = this.network.getCustomerDirectory().findCustomer(user.getUserId());
        if(c.getProperty().getID() == null){
            JOptionPane.showMessageDialog(null, "You do not have any properties yet. But you can rent one right away!! :) ");

        }
        else{
            tableModel.setRowCount(0);

                Object[] row = new Object[10];

                row[0] = c.getProperty();
                row[1] = c.getProperty().getNo_of_rooms();
                row[2] = c.getProperty().getNo_of_bathrooms();
                row[3] = c.getProperty().getFull_address();
                row[4] = c.getProperty().getPrice();
                row[5] = c.getProperty().getLease().getStart_date();
                row[6] = c.getProperty().getLease().getType();
                row[7] = c.getProperty().getLease().getIsLeaseSigned();

                tableModel.addRow(row);


            fieldTotalRentPrice.setText(String.valueOf(c.getRentalsTotal()));           
        }

    }
    
    private void formatRows() {

        jTable2.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = String.valueOf(tableModel.getValueAt(row, 7));
                c.setBackground(status.equals("True") ? Color.GREEN : Color.WHITE);
                return c;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fieldTotalRentPrice = new javax.swing.JTextField();
        LeaseBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(41, 67, 138));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapmarker.png"))); // NOI18N
        jButton3.setText("View Location");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 40));

        jTable2.setForeground(new java.awt.Color(41, 67, 138));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property ID", "No of Rooms", "No of Bathrooms", "Address", "Rent price", "Start Date", "Lease Type", "Lease Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 770, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("Total Rent over lease period :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 20));

        fieldTotalRentPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTotalRentPriceActionPerformed(evt);
            }
        });
        add(fieldTotalRentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 140, 30));

        LeaseBtn.setBackground(new java.awt.Color(41, 67, 138));
        LeaseBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LeaseBtn.setForeground(new java.awt.Color(255, 255, 255));
        LeaseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        LeaseBtn.setText("Upload Signed Lease Agreement Document");
        LeaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaseBtnActionPerformed(evt);
            }
        });
        add(LeaseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 300, 40));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 67, 138));
        jLabel2.setText("Customer Current Property");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img2.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 590, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int selectedRow = jTable2.getSelectedRow();

        if(selectedRow >= 0){
            this.selectedProperty = (Property) jTable2.getValueAt(selectedRow, 0);

            GMapsFrame gMapsFrame = new GMapsFrame(selectedProperty);
            gMapsFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            gMapsFrame.setVisible(true);
//            new GMapsFrame(gMapsFrame, selectedProperty);

        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row ");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void LeaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaseBtnActionPerformed
        // TODO add your handling code here:
        Customer c = this.network.getCustomerDirectory().findCustomer(user.getUserId());
        JFileChooser fileChooser = new JFileChooser();
        
        int response = fileChooser.showOpenDialog(this);
        
        if (response == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String fileName = selectedFile.getName();

            // Save file to project directory
            String projectDirectory = System.getProperty("user.dir");
//            System.out.println(projectDirectory);
            Path sourcePath = selectedFile.toPath();
            Path targetPath = new File(projectDirectory + "/src/LeaseAgreements/" + fileName).toPath();
//            System.out.println(targetPath);
            try {
                Files.copy(sourcePath, targetPath, StandardCopyOption.REPLACE_EXISTING);
                JOptionPane.showMessageDialog(null, "File saved to System!");
                
                // Saving the path of the lease document as a string to the Lease doc variable of class 'Lease'. 
                // This pertains to specific customer.
                c.getProperty().getLease().setLeaseDoc(String.valueOf(targetPath));
                
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }       
        
    }//GEN-LAST:event_LeaseBtnActionPerformed

    private void fieldTotalRentPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTotalRentPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTotalRentPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LeaseBtn;
    private javax.swing.JTextField fieldTotalRentPrice;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
