/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Network;
import Business.PropertyManagement.ServiceRequest;
import Business.User.User;
import Business.User.UserDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ElectricityServiceJPanel extends javax.swing.JPanel {

    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel; 
    
    public ElectricityServiceJPanel() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
    }
    
    public ElectricityServiceJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        Customer cust = this.network.getCustomerDirectory().findCustomer(user.getUserId());
        
        showServices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        sendRequestjBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("Service Request History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electricity", "WIFI", "Plumbing", "Maintainence" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 67, 138));
        jLabel3.setText("Explain your issue: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 560, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(41, 67, 138));
        jLabel4.setText("Type of service: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        sendRequestjBtn.setBackground(new java.awt.Color(41, 67, 138));
        sendRequestjBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendRequestjBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendRequestjBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        sendRequestjBtn.setText("Send Request");
        sendRequestjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestjBtnActionPerformed(evt);
            }
        });
        add(sendRequestjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 150, 40));

        jTable1.setForeground(new java.awt.Color(41, 67, 138));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service ID", "Service Type", "Service Status", "Service Description"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 870, 110));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(41, 67, 138));
        jLabel5.setText("Services");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maintainencepeople-1.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 620, 210));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wire Fixing", "WIFI is not working", "Heater is not working", "AC is not working", "General Maintaniance", "Pipe Leakage", "Gs Leakage", "Electric Appliance Repair", "Floor Fixing", "Wall Fixing", "Door Fixing" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 240, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(41, 67, 138));
        jLabel6.setText("Type of service: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sendRequestjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestjBtnActionPerformed
        // TODO add your handling code here:
        Customer cust = this.network.getCustomerDirectory().findCustomer(user.getUserId());
        
        String service = jComboBox1.getSelectedItem().toString();
        String subject = jComboBox2.getSelectedItem().toString();
        String desc = jTextArea1.getText();
        
        if (service != null && subject != null && desc != null){
            ServiceRequest sr = this.network.getServicerequestdirectory().customerServicerequest(cust, service, subject, desc, "Request Sent", 0);
        } else {
            JOptionPane.showMessageDialog(null, "Please enter correct service details ");
        }
        
        //jComboBox1.se;
        jTextArea1.setText("");
        showServices();
    }//GEN-LAST:event_sendRequestjBtnActionPerformed

    public void showServices(){
        
        tableModel.setRowCount(0);
        // System.out.println(this.network.getPropertyDirectory().getProperties().size());
        for(ServiceRequest sr : this.network.getServicerequestdirectory().getServicerequestlist()){
            if(sr.getCustomer().getUserId().equals(this.user.getUserId())){
                Object[] row = new Object[6];

                    row[0] = sr.toString();
                    row[1] = sr.getService_type();
                    row[2] = sr.getService_subject();
                    row[3] = sr.getService_desc();
                    row[4] = sr.getService_status();
                    
                    if(sr.getServiceprovider() != null){
                        row[5] = sr.getServiceprovider().getFullName();
                    } else {
                        row[5] = "No Service Provider Assigned";
                    }

                    tableModel.addRow(row);
            } else {
                if(tableModel.getRowCount() < 0){
                    JOptionPane.showMessageDialog(null, "You have no service request, Please Request any service if you are in any Issues");
                }
            }                     
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton sendRequestjBtn;
    // End of variables declaration//GEN-END:variables
}
