/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Network;
import Business.Recreation.Booking;
import Business.Recreation.Room;
import Business.Services.RentalRequest;
import Business.User.User;
import Business.User.UserDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ViewCustomerCurrentBookingsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomers
     */
    
    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel2; 
    String selectedBooking ;
    
    public ViewCustomerCurrentBookingsJPanel() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
        
    }
    
    public ViewCustomerCurrentBookingsJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel2 = (DefaultTableModel) jTable2.getModel();
        
        populate();
        
    }
    
    
    public void populate() {
        
        Customer c = this.network.getCustomerDirectory().findCustomer(user.getUserId());

        tableModel2.setRowCount(0);
        for(Room r : this.network.getRoomDirectory().getRooms()){
            for(Booking b : r.getBookings()){
                if(b.getCustomer().getUserId().equals(c.getUserId())){
                   Object[] row = new Object[10];

                   row[0] = b.getID();
                   row[1] = r.getRoomID();
                   row[2] = b.getCustomer().getUserId();
                   row[3] = b.getCustomer().getFullName();
                   row[4] = b.getDate();
                   row[5] = b.getStart_time();
                   row[6] = b.getEnd_time();

                    tableModel2.addRow(row);                  
                }

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Room ID", "Customer ID", "Customer Name", "Date booked", "From time", "To time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 770, 140));

        jButton1.setBackground(new java.awt.Color(41, 67, 138));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton1.setText("Delete Booking for Selected Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 260, 50));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("View Customer Current Bookings");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/custBookings.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 570, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Customer c = this.network.getCustomerDirectory().findCustomer(user.getUserId());
        
        int selectedrow = jTable2.getSelectedRow();

        if(selectedrow >= 0){
            this.selectedBooking = (String) jTable2.getValueAt(selectedrow, 0);
            for(Room r : this.network.getRoomDirectory().getRooms()){
                Booking booking = r.findBookingByID(selectedBooking);
                if(booking != null){
                   for(Booking b : r.getBookings()){
                       if(b.getID().equals(booking.getID())){
                           r.getBookings().remove(b);
                           break;
                       }
                   }                   
                }
            }    
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row ");
        } 
        
        populate();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
