/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PropertyManager;

import Business.EcoSystem;
import Business.Network;
import Business.PropertyManagement.ServiceProvider;
import Business.PropertyManagement.ServiceRequest;
import Business.PropertyManagement.ServiceRequestDirectory;
import Business.User.User;
import Business.User.UserDirectory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.MutableComboBoxModel;
import javax.swing.table.DefaultTableModel;


public class AssignServiceProviderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignServiceProviderJPanel
     */
    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel1;
    DefaultTableModel tableModel2;
    
    public AssignServiceProviderJPanel() {
        initComponents();
        
        this.setVisible(true);
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
    }

    public AssignServiceProviderJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel1 = (DefaultTableModel) jTable1.getModel();
        this.tableModel2 = (DefaultTableModel) jTable2.getModel();
        
        populateRequest();
        populateAssignedList();
        serviceProviders();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateRequest(){
        tableModel1.setRowCount(0);
        // System.out.println(this.network.getPropertyDirectory().getProperties().size());
        for(ServiceRequest sr : this.network.getServicerequestdirectory().getServicerequestlist()){
            
            if (sr.getServiceprovider() == null){
                    Object[] row = new Object[4];

                    row[0] = sr;
                    row[1] = sr.getService_type();
                    row[2] = sr.getService_subject();
                    row[3] = sr.getCustomer().getFullName();

                    tableModel1.addRow(row);
            }                         
        }
    }
    
    public void populateAssignedList(){
        tableModel2.setRowCount(0);
        // System.out.println(this.network.getPropertyDirectory().getProperties().size());
        for(ServiceRequest sr : this.network.getServicerequestdirectory().getServicerequestlist()){
            if(sr.getServiceprovider() != null){
                Object[] row = new Object[6];

                    row[0] = sr;
                    row[1] = sr.getService_type();
                    row[2] = sr.getServiceprovider().getFullName();
                    row[3] = sr.getCustomer().getFullName();
                    row[4] = sr.getService_price();
                    row[5] = sr.getService_status();

                    tableModel2.addRow(row);
            }
        }
    }
    
    public void serviceProviders() {
        MutableComboBoxModel<String> model = new DefaultComboBoxModel<String>();
        
        for (ServiceProvider sp : network.getServiceproviderdir().getServiceProviderList()) {
            model.addElement(sp.getFullName());
        }
        
        jComboBox1.setModel(model);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(41, 67, 138));
        jLabel5.setText("Assign Service Provider");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("Select Service Provider:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 150, -1));

        jButton1.setBackground(new java.awt.Color(41, 67, 138));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jButton1.setText("Assign");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 100, 40));

        jTable2.setForeground(new java.awt.Color(41, 67, 138));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Service ID", "Service Type", "Service Provider", "Customer Name", "Cost", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 1110, 120));

        jTable1.setForeground(new java.awt.Color(41, 67, 138));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service ID", "Service Type", "Service Subject", "Customer Name"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 650, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/servicepro.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 550, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ServiceRequestDirectory srd = this.network.getServicerequestdirectory();
        
        int selectedServiceRequest = jTable1.getSelectedRow();
        String servicerequesID = tableModel1.getValueAt(selectedServiceRequest, 0).toString();
        
        String selectedServiceProviderID = jComboBox1.getSelectedItem().toString();
        ServiceProvider selectedserviceprovider = network.getServiceproviderdir().findServiceProviderbyName(selectedServiceProviderID);
        
        if(jComboBox1.getSelectedItem() != null) {
            
            if(selectedServiceRequest <= 0) {
                
                for (ServiceRequest sr : srd.getServicerequestlist()){
                   
                    if(srd.findServiceReqByID(servicerequesID) != null){
                        ServiceRequest nsr = srd.findServiceReqByID(servicerequesID);
                        nsr.setServiceprovider(selectedserviceprovider);
                        nsr.setService_status("Service Provider Assigned");
                   }
                    populateRequest();
                    populateAssignedList();
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Please Selected the Priority Service request");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select Valid Service provider");
        }

        for(ServiceRequest sr : this.network.getServicerequestdirectory().getServicerequestlist()){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
