/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PropertyManager;

import Business.EcoSystem;
import Business.Network;
import Business.PropertyManagement.ServiceProvider;
import Business.PropertyManagement.ServiceProviderDirectory;
import Business.User.User;
import Business.User.UserDirectory;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CreateServiceProvidersJPanel extends javax.swing.JPanel {

    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel1;
    
    public CreateServiceProvidersJPanel() {
        initComponents();
        
        this.setVisible(true);
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
    }
    
    public CreateServiceProvidersJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel1 = (DefaultTableModel) jTable1.getModel();
        
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        roleSelectionjComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 67, 138));
        jLabel1.setText("Create Service Providers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 67, 138));
        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 90, -1));

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });
        add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 130, 30));
        add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 130, 30));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 130, 30));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 120, 30));

        btnRegister.setBackground(new java.awt.Color(41, 67, 138));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        btnRegister.setText("Create Service Provider");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 220, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 67, 138));
        jLabel3.setText("User Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(41, 67, 138));
        jLabel4.setText("Last Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(41, 67, 138));
        jLabel5.setText("Password:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 80, -1));
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(41, 67, 138));
        jLabel11.setText("Phone Number:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 93, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(41, 67, 138));
        jLabel14.setText("Role:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 80, -1));

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });
        add(txtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 140, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(41, 67, 138));
        jLabel10.setText("Age:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 50, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 130, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "UserID", "Role", "Full Name", "Username", "Password", "Phone", "Email", "Age"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 1220, 130));

        roleSelectionjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrician", "Plumbers", "Maintanance Team", "Canteen Manager", "Laundary Manager" }));
        add(roleSelectionjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 210, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(41, 67, 138));
        jLabel15.setText("Email Address:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 100, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/createservpro.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 600, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        //        // TODO add your handling code here:

        UUID uuid = UUID.randomUUID();
        String randomUUIDString = uuid.toString();

        String firstName = txtFName.getText();
        String lastName = txtLName.getText();
        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        Integer age = Integer.valueOf(txtAge.getText());
        Long phoneNumber = Long.valueOf(txtPhoneNumber.getText());
        String userId = randomUUIDString;
        String emailAddress = txtEmailAddress.getText();
        String role = roleSelectionjComboBox.getSelectedItem().toString();

        if (firstName.isEmpty() || lastName.isEmpty() || userName.isEmpty()|| password.isEmpty()
            || txtAge.getText().isEmpty()|| userId.isEmpty()|| txtPhoneNumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all details !");
            clearAllFields();
            return;
        }

        if (validatePhoneNumber(txtPhoneNumber.getText()) == null) {
            JOptionPane.showMessageDialog(this, "Please enter a valid phone number !");
            return;
        }

        if(validateEmailAddress(emailAddress) == null) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address !");
            return;
        }

        if (validateAge(txtAge.getText()) == null) {
            JOptionPane.showMessageDialog(this, "Please enter a valid age!");
            return;
        }

        this.userDirectory.createUserAccount(userName, password, role, userId);
        ServiceProviderDirectory ServiceProviderDirectory = this.network.getServiceproviderdir();
        
        ServiceProviderDirectory.createServiceProvider(userId, firstName, lastName, userName, password, age, emailAddress, phoneNumber, role);
        System.out.println("UD size : "  + this.userDirectory.getUsers().size());
        System.out.println("ED size : "  + ServiceProviderDirectory.getServiceProviderList().size());

        clearAllFields();
        populateTable();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private Integer validateAge(String age) {
        try {
            return Integer.parseInt(age);
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            return null;
        }
    }
    
    private Long validatePhoneNumber(String phoneNumber) {
        try {

            String cellPhoneNumberRegex = "^\\d{10}$";

            Pattern cellPhoneNumberPattern = Pattern.compile(cellPhoneNumberRegex);
            Matcher cellPhoneNumberMatcher = cellPhoneNumberPattern.matcher(phoneNumber);

            if (cellPhoneNumberMatcher.matches()) {
                return Long.parseLong(phoneNumber);
            } else {
                //JOptionPane.showMessageDialog(this, "Invalid Phone Number!");
                return null;
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            return null;
        }

    }
    
    private String validateEmailAddress(String emailAddress) {
        try {

            String emailAddressRegex = "^(.+)@(\\S+)$";

            Pattern emailPattern = Pattern.compile(emailAddressRegex);
            Matcher emailMatcher = emailPattern.matcher(txtEmailAddress.getText());

            if (emailMatcher.matches()) {
                return emailAddress;
            } else {
//                JOptionPane.showMessageDialog(this, "Invalid Email Address!");
                return null;
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> roleSelectionjComboBox;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void clearAllFields() {
        txtAge.setText("");
        txtFName.setText("");
        txtLName.setText("");
        txtPassword.setText("");
        txtPhoneNumber.setText("");
        txtUserName.setText("");
        txtEmailAddress.setText("");
    }

    public void populateTable(){
        
        tableModel1.setRowCount(0);
        ServiceProviderDirectory spd = this.network.getServiceproviderdir();
        
        for(ServiceProvider sp : spd.getServiceProviderList()){
            Object row[] = new Object[8];
            row[0] = sp.getUserId().toString();
            row[1] = sp.getRole();
            row[2] = sp.getFullName();
            row[3] = sp.getUserName();
            row[4] = sp.getPassword();
            row[5] = sp.getPhoneNumber();
            row[6] = sp.getEmailId();
            row[7] = sp.getAge();
            
            tableModel1.addRow(row);
        }
        
    }
}
