/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Recreation;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Network;
import Business.Recreation.Room;
import Business.Services.RentalRequest;
import Business.User.User;
import Business.User.UserDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shalom Daniel <your.name at your.org>
 */
public class AddRoomsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomers
     */
    
    private EcoSystem ecosystem;
    private Network network;
    private User user;
    private UserDirectory userDirectory;
    DefaultTableModel tableModel; 
    Room selectedRoom ;
    
    public AddRoomsJPanel() {
        initComponents();
        
        this.ecosystem = this.ecosystem.getInstance();
        this.network = this.ecosystem.getNetwork();
        this.userDirectory = this.network.getUserDirectory();
        
    }
    
    public AddRoomsJPanel(EcoSystem ecosystem, User user) {
        initComponents();
        this.setVisible(true);

        this.user = user;
        this.ecosystem = ecosystem;
        this.userDirectory = this.ecosystem.getNetwork().getUserDirectory();
        this.network = this.ecosystem.getNetwork();
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        
        populate();
        
    }
    
    
    
    public void populate() {
        
        tableModel.setRowCount(0);
        for(Room r : this.network.getRoomDirectory().getRooms()){
                    
                   Object[] row = new Object[10];

                   row[0] = r.getRoomID();
                   row[1] = r.getAvailability(); 
                   row[2] = r.getNo_of_requests();

                   tableModel.addRow(row);                   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fieldRoomID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setForeground(new java.awt.Color(41, 67, 138));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Current Availability ", "No. of times Room booked "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 640, 110));

        jButton1.setBackground(new java.awt.Color(41, 67, 138));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton1.setText("Add Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 160, 40));

        jLabel2.setText("Room ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, 20));

        fieldRoomID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRoomIDActionPerformed(evt);
            }
        });
        add(fieldRoomID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 140, 40));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 67, 138));
        jLabel3.setText("Add Recreation Room");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 240, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recreationroom.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 610, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldRoomIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRoomIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRoomIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(fieldRoomID.getText().equals(null)){
            JOptionPane.showMessageDialog(null, " Please add the Room ID! ");
        }else{
            this.network.getRoomDirectory().createRoom(fieldRoomID.getText(), true);
            populate();          
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldRoomID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
